const tutor = {
  cat: "補習",
  index: 0,
  items: {
    General: "全科",
    Arts: "文科",
    Science: "理科",
    Commerce: "商科",
    ChineseLanguage: "中文",
    EnglishLanguage: "英文",
    Mathematics: "數學",
    MathematicsM1: "數學(M1)",
    MathematicsM2: "數學(M2)",
    ChineseLiterature: "中國文學",
    EnglishLiterature: "英國文學",
    ChineseHistory: "中國歷史",
    WorldHistory: "世界歷史",
    Geography: "地理",
    LiberalStudies: "通識教育",
    IntegratedScience: "綜合科學",
    IntegratedHumanities: "綜合人文學",
    AdditionalMathematics: "附加數學",
    PureMathematics: "純粹數學",
    AppliedMathematics: "應用數學",
    Physics: "物理",
    Biology: "生物",
    Chemistry: "化學",
    BusinessStudies: "商業學",
    Accounting: "會計",
    Economics: "經濟",
    IntroductiontoBusiness: "企業概論",
    GovernmentandPublicAffairs: "政府及公共事務",
    MathematicsandStatistics: "數學及統計學",
    BAFS: "BAFS",
  },
};
const oral = {
  cat: "會話",
  index: 1,
  items: {
    Mandarin: "普通話",
    Cantonese: "廣東話",
    EnglishPinyin: "英文拼音",
    Japanese: "日語",
    Korean: "韓語",
    French: "法語",
    Italian: "意大利語",
    German: "德語",
    Spanish: "西班牙語",
    EnglishConversation: "英語會話",
    GCE: "GCE",
    TOEFL: "TOEFL",
    IELTS: "IELTS",
  },
};

const music = {
  cat: "音樂",
  index: 2,
  items: {
    Cello: "大提琴",
    Viola: "中提琴",
    Violin: "小提琴",
    Trumpet: "小號",
    Harmonica: "口琴",
    Recorder: "木笛",
    Flute: "長笛",
    Panflute: "牧童笛",
    Clarinet: "單簧管",
    Saxophone: "色士風",
    Erhu: "二胡",
    Guzheng: "古箏",
    Pipa: "琵琶",
    Yangqin: "揚琴",
    Liuqin: "柳琴",
    Guitar: "結他",
    AcousticGuitar: "木結他",
    ElectricGuitar: "電結他",
    ElectronicKeyboard: "電子琴",
    Piano: "鋼琴",
    Vocal: "聲樂",
    MusicTheory: "樂理",
  },
};

const others = {
  cat: "其他",
  index: 3,
  items: {
    SwimmingFreestyle: "游水(蛙式)",
    SwimmingBackstroke: "游水(自由式)",
    SwimmingButterfly: "游水(背泳)",
    SwimmingBreaststroke: "游水(蝶式)",
    Painting: "繪畫",
    Computer: "電腦",
    CambridgeEnglish: "劍橋英語",
    OlympiadMath: "奧數",
    Abacus: "珠心算",
    MathematicsXueLin: "學林數學",
    IGCSE: "IGCSE",
    IBOthers: "IB其他",
  },
};

const subjects = [tutor, oral, music, others];

export default subjects;
